### ISSUE TITLE
POC: Use CSS to describe board

### ISSUE THREAD

**Issue by MartinHelmut** [sinnerschrader/push-the-button#1]
```css
@keyframes pulse {
  0% { color: orange; }
  100% { color: purple; }
}

board { /* ... */ }

pixel {
  animation: pulse 5s infinite;
}

/* First pixel */
pixel:nth-child(1) {
  color: blue;
}

pixel:nth-child(1) {
  transform: translateX(2px);
}
```
